name: adaptive_test
description: >-
  A Flutter package to generate adaptive golden files during widget tests.
version: 0.1.0
homepage: https://github.com/bamlab/adaptive_test
repository: https://github.com/bamlab/adaptive_test

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  path: ^1.8.1
  test_api: ^0.4.9
  meta: ^1.7.0
  cupertino_icons: ^1.0.4
  recase: ^4.0.0
  equatable: ^2.0.3
  file: ^6.1.2
  platform: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
    - assets/keyboards/