name: adaptive_test
description: >-
  A Flutter package to generate adaptive golden files during widget tests.
version: 0.7.2
homepage: https://github.com/bamlab/adaptive_test
repository: https://github.com/bamlab/adaptive_test

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  package_config: ^2.1.0
  path: ^1.8.2
  platform: ^3.1.0
  recase: ^4.0.0

dev_dependencies:
  theodo_analysis: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
    - assets/keyboards/
