name: multi_packages_example_app
description: A multi packages Flutter app to illustrate the package adaptive_test. This "multi_packages_app" package holds the app related code

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  multi_packages_example_theme:
    path: '../theme'

dev_dependencies:
  flutter_test:
    sdk: flutter
  adaptive_test:
    path: ../../../

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dash.png